/**
 * Registers the service worker generated by @vite-pwa/nuxt.
 *
 * The module generates `sw.js` and the web manifest, but its own registration
 * injection does not reach the SSR HTML of this app (custom `app.head`), so the
 * registration is explicit here. `registerType: 'autoUpdate'` keeps the worker
 * updating itself on the next load.
 */
export default defineNuxtPlugin(() => {
  if (!('serviceWorker' in navigator)) {
    return
  }

  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch(() => {
      // offline support is optional: ignore registration failures
    })
  })
})
