language: node_js

sudo: false

# master为hexo博客所在分支
branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_5ff8ca309359_key -iv $encrypted_5ff8ca309359_iv
  -in .travis/id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'JounQin'
- git config --global user.email 'liujiaren1992@vip.qq.com'

install:
- npm install hexo-cli -g
- npm install

script:
- hexo clean
- hexo g
- hexo d